# Generated by Django 3.2.4 on 2021-07-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteTaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creating_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
